<?php

namespace Database\Seeders;

use App\Models\File;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class FileClients extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $news = [
            // 20 líneas de datos aleatorios
            [
                'filename' => 'file1.pdf',
                'nombre_cliente' => 'Cliente Uno',
                'dni' => '12345678A',
                'email' => 'cliente1@example.com',
                'telefono' => '600123456',
                'fechaFirma' => '2024-12-19',
                'anyoNacimiento' => '1985',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file2.pdf',
                'nombre_cliente' => 'Cliente Dos',
                'dni' => '23456789B',
                'email' => 'cliente2@example.com',
                'telefono' => '600234567',
                'fechaFirma' => '2024-12-18',
                'anyoNacimiento' => '1990',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file3.pdf',
                'nombre_cliente' => 'Cliente Tres',
                'dni' => '34567890C',
                'email' => 'cliente3@example.com',
                'telefono' => '600345678',
                'fechaFirma' => '2024-12-17',
                'anyoNacimiento' => '1978',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file4.pdf',
                'nombre_cliente' => 'Cliente Cuatro',
                'dni' => '45678901D',
                'email' => 'cliente4@example.com',
                'telefono' => '600456789',
                'fechaFirma' => '2024-12-16',
                'anyoNacimiento' => '1982',
                'short_id' => Str::random(8),
                'client_kind' => 'red',
            ],
            [
                'filename' => 'file5.pdf',
                'nombre_cliente' => 'Cliente Cinco',
                'dni' => '56789012E',
                'email' => 'cliente5@example.com',
                'telefono' => '600567890',
                'fechaFirma' => '2024-12-15',
                'anyoNacimiento' => '1995',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file6.pdf',
                'nombre_cliente' => 'Cliente Seis',
                'dni' => '67890123F',
                'email' => 'cliente6@example.com',
                'telefono' => '600678901',
                'fechaFirma' => '2024-12-14',
                'anyoNacimiento' => '1988',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file7.pdf',
                'nombre_cliente' => 'Cliente Siete',
                'dni' => '78901234G',
                'email' => 'cliente7@example.com',
                'telefono' => '600789012',
                'fechaFirma' => '2024-12-13',
                'anyoNacimiento' => '1975',
                'short_id' => Str::random(8),
                'client_kind' => 'red',
            ],
            [
                'filename' => 'file8.pdf',
                'nombre_cliente' => 'Cliente Ocho',
                'dni' => '89012345H',
                'email' => 'cliente8@example.com',
                'telefono' => '600890123',
                'fechaFirma' => '2024-12-12',
                'anyoNacimiento' => '1992',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file9.pdf',
                'nombre_cliente' => 'Cliente Nueve',
                'dni' => '90123456I',
                'email' => 'cliente9@example.com',
                'telefono' => '600901234',
                'fechaFirma' => '2024-12-11',
                'anyoNacimiento' => '1980',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file10.pdf',
                'nombre_cliente' => 'Cliente Diez',
                'dni' => '01234567J',
                'email' => 'cliente10@example.com',
                'telefono' => '600012345',
                'fechaFirma' => '2024-12-10',
                'anyoNacimiento' => '1970',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file11.pdf',
                'nombre_cliente' => 'Cliente Once',
                'dni' => '11234567K',
                'email' => 'cliente11@example.com',
                'telefono' => '600112345',
                'fechaFirma' => '2024-12-09',
                'anyoNacimiento' => '1983',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file12.pdf',
                'nombre_cliente' => 'Cliente Doce',
                'dni' => '21234567L',
                'email' => 'cliente12@example.com',
                'telefono' => '600212345',
                'fechaFirma' => '2024-12-08',
                'anyoNacimiento' => '1991',
                'short_id' => Str::random(8),
                'client_kind' => 'red',
            ],
            [
                'filename' => 'file13.pdf',
                'nombre_cliente' => 'Cliente Trece',
                'dni' => '31234567M',
                'email' => 'cliente13@example.com',
                'telefono' => '600312345',
                'fechaFirma' => '2024-12-07',
                'anyoNacimiento' => '1989',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file14.pdf',
                'nombre_cliente' => 'Cliente Catorce',
                'dni' => '41234567N',
                'email' => 'cliente14@example.com',
                'telefono' => '600412345',
                'fechaFirma' => '2024-12-06',
                'anyoNacimiento' => '1979',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file15.pdf',
                'nombre_cliente' => 'Cliente Quince',
                'dni' => '51234567O',
                'email' => 'cliente15@example.com',
                'telefono' => '600512345',
                'fechaFirma' => '2024-12-05',
                'anyoNacimiento' => '1984',
                'short_id' => Str::random(8),
                'client_kind' => 'red',
            ],
            [
                'filename' => 'file16.pdf',
                'nombre_cliente' => 'Cliente Dieciséis',
                'dni' => '61234567P',
                'email' => 'cliente16@example.com',
                'telefono' => '600612345',
                'fechaFirma' => '2024-12-04',
                'anyoNacimiento' => '1986',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file17.pdf',
                'nombre_cliente' => 'Cliente Diecisiete',
                'dni' => '71234567Q',
                'email' => 'cliente17@example.com',
                'telefono' => '600712345',
                'fechaFirma' => '2024-12-03',
                'anyoNacimiento' => '1994',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file18.pdf',
                'nombre_cliente' => 'Cliente Dieciocho',
                'dni' => '81234567R',
                'email' => 'cliente18@example.com',
                'telefono' => '600812345',
                'fechaFirma' => '2024-12-02',
                'anyoNacimiento' => '1987',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
            [
                'filename' => 'file19.pdf',
                'nombre_cliente' => 'Cliente Diecinueve',
                'dni' => '91234567S',
                'email' => 'cliente19@example.com',
                'telefono' => '600912345',
                'fechaFirma' => '2024-12-01',
                'anyoNacimiento' => '1977',
                'short_id' => Str::random(8),
                'client_kind' => 'red',
            ],
            [
                'filename' => 'file20.pdf',
                'nombre_cliente' => 'Cliente Veinte',
                'dni' => '01234567T',
                'email' => 'cliente20@example.com',
                'telefono' => '600012345',
                'fechaFirma' => '2024-11-30',
                'anyoNacimiento' => '1993',
                'short_id' => Str::random(8),
                'client_kind' => 'blue',
            ],
        ];

        foreach ($news as $new) {
            File::create($new);
        }
    }
}
