version: '3'
services:
    laravel:
        container_name: laravel-container
        build:
            context: .
            dockerfile: /home/eks/tfg-1/Dockerfile
        image: sail-8.2/app
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            APP_ENV: "${APP_ENV}"
            APP_URL: "${APP_URL}"
        networks:
            - sail
        depends_on:
            - mysql

    nginx:
        image: nginx:1.19.0
        container_name: nginx-container
        restart: unless-stopped
        build:
            context: .
            dockerfile: /home/eks/tfg-1/nginx/Dockerfile
        volumes:
            - /home/eks/tfg-1/nginx/nginx.conf:/etc/nginx/default.conf
            - /home/eks/tfg-1/docker/certbot/_1conf:/etc/letsencrypt
            - /home/eks/tfg-1/docker/certbot/www:/var/www/certbot
            - /home/eks/tfg-1/public:/var/www/html
        ports:
            - 80:80
            - 443:443
        depends_on:
            - laravel
        networks:
            - sail

    # certbot:
    #     image: certbot/certbot
    #     container_name: certbot
    #     volumes: 
    #         - ./docker/certbot/conf:/etc/letsencrypt
    #         - ./docker/certbot/www:/var/www/certbot
    #     command: certbot renew
    #     networks:
    #         - sail

    mysql:
        container_name: mysql-container
        image: 'mysql/mysql-server:8.0' 
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
